name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Mostrar información del servidor
        run: |
          echo "Runner funcionando correctamente"
          echo "Hostname:"
          hostname
          echo "Usuario:"
          whoami
          echo "Docker:"
          docker --version
          echo "Contenedores:"
          docker ps
